on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run linter
        run: |
          docker build . -t linter -f ./Dockerfile
          docker run linter
